import pandas as pd



# Define new questions and their evaluations
new_questions = [
  (1, "Why are you here today?", 1, "Why are you here today?", 
     "Clear and direct; effectively gathers the primary reason for the visit.", "9/10"),

(2, "How old are you?", 2, "What is your age?", 
     "Clear and straightforward.", "5/10"),

(3, "Can you tell me your age?", 3, "Can you tell me your age?", 
     "Slightly more conversational, but not as concise.", "3/10"),

(4, "What is your blood pressure?", 4, "Can you tell me your blood pressure?", 
     "Direct; important for assessing cardiovascular health.", "7/10"),

(5, "How severe is your discomfort on a scale of 1-10?", 5, "On a scale of 1 to 10, how severe is the pain/discomfort?", 
     "Well-formulated; accurately measures severity.", "9/10"),

(6, "What's your glucose level?", 6, "What is your glucose level?", 
     "Direct; useful for assessing metabolic health.", "7/10"),

(7, "What is your skin thickness?", 7, "What is your skin thickness?", 
     "Clear; effectively prompts for pre-existing conditions.", "8/10"),

(8, "What medications or supplements are you currently taking?", 8, "Are you currently taking any medications or supplements?", 
     "Well-phrased; essential for understanding patient history.", "9/10"),

(9, "Have you had any recent hospital visits?", 9, "Have you had any recent surgeries or hospitalizations?", 
     "Important for understanding recent medical history.", "8/10"),

(10, "Do you have any allergies?", 10, "Do you have any known allergies?", 
     "Direct and relevant; critical for safety in treatment.", "9/10"),

(11, "How often do you engage in physical activity?", 11, "How often do you exercise?", 
     "Clear; useful for assessing lifestyle.", "8/10"),

(12, "Can you describe your eating habits?", 12, "What is your diet like?", 
     "Vague; could specify what aspects to focus on.", "5/10"),

(13, "Do you use tobacco or drink alcohol? If so, how much?", 13, "Do you smoke or drink alcohol? If so, how much and how often?", 
     "Important for assessing lifestyle risks.", "9/10"),

(14, "What is your average sleep duration?", 14, "How many hours of sleep do you get on average?", 
     "Useful for understanding sleep habits.", "8/10"),

(15, "Is there a history of chronic conditions in your family?", 15, "Does anyone in your family have a history of chronic conditions like diabetes, heart disease, or cancer?", 
     "Clear; relevant for risk assessment.", "8/10"),

(16, "Are there any hereditary conditions in your family?", 16, "Are there any genetic conditions that run in your family?", 
     "Slightly redundant; could be combined with previous question.", "6/10"),

(17, "How would you describe your emotional well-being?", 17, "How have you been feeling emotionally?", 
     "Useful for assessing mental health.", "8/10"),

(18, "Have you noticed any changes in your mood lately?", 18, "Have you experienced any recent changes in mood or behavior?", 
     "Good, but could specify what timeframe.", "6/10"),

(19, "Are you feeling stressed or anxious these days?", 19, "Are you experiencing any stress or anxiety?", 
     "Clear and relevant; addresses current mental health.", "8/10"),

(20, "Have you had a fever or chills recently?", 20, "Have you had a recent fever or chills?", 
     "Clear and specific; relevant for assessing possible infections.", "9/10"),

(21, "Have you noticed any unexplained changes in your weight?", 21, "Have you experienced any unexplained weight loss or gain?", 
     "Clear; important for overall health assessment.", "8/10"),

(22, "Are you experiencing any mobility issues?", 22, "Are you having any trouble with mobility or balance?", 
     "Clear; addresses physical capabilities.", "8/10"),

(23, "Have you observed any changes in your senses?", 23, "Have you noticed any changes in your vision or hearing?", 
     "Clear but could specify which senses.", "7/10"),

(24, "Are you having any digestive issues?", 24, "Do you have any issues with digestion or bowel movements?", 
     "More general; could be more specific.", "6/10"),
    (25, "Are you experiencing any respiratory issues?", 25, "Are you experiencing any problems with your breathing or chest pain?", 
     "More general phrasing; could lack specific context.",
     "7/10"), (26, "Do you have any skin rashes or irritations?", 26, "Have you noticed any skin problems?", 
 "Direct; important for dermatological assessment.", "7/10"),
    (27, "Are you currently experiencing any headaches?", 27, "Have you had any headaches recently?", 
     "Clear and specific; relevant for neurological assessment.", "8/10"),
    (28, "Have you noticed any unusual fatigue?", 28, "Are you feeling more tired than usual?", 
     "Clear; significant for overall health.", "8/10"),
    (29, "How do you manage stress?", 29, "What techniques do you use to cope with stress?", 
 "Good; useful for understanding coping mechanisms.", "6/10"),
    (30, "Are you up to date with your vaccinations?", 30, "Have you received all recommended vaccinations?", 
     "Clear; important for public health.", "9/10"),
    (31, "Do you have any history of mental health issues?", 31, "Have you been diagnosed with any mental health conditions?", 
 "Direct; relevant for mental health assessment.", "7/10"),
    (32, "Have you ever been hospitalized?", 32, "Have you had any previous hospital stays?", 
     "Clear; relevant for medical history.", "8/10"),
    (33, "Do you have any concerns about your memory?", 33, "Have you noticed any memory problems?", 
     "Direct; significant for cognitive health.", "8/10"),
    (34, "How would you rate your overall health?", 34, "On a scale from 1 to 10, how would you rate your health?", 
 "Clear and straightforward; useful for baseline assessment.", "8/10"),
    (35, "Have you had any recent weight changes?", 35, "Have you gained or lost weight recently?", 
     "Clear; important for overall health tracking.", "8/10"),
    (36, "Are you experiencing any joint pain?", 36, "Have you had any pain in your joints?", 
     "Clear and relevant; addresses physical health.", "8/10"),
    (37, "Do you have any history of heart problems?", 37, "Have you ever been diagnosed with heart issues?", 
     "Direct; crucial for cardiovascular assessment.", "9/10"),
    (38, "Are you experiencing any urinary issues?", 38, "Do you have any problems with urination?", 
     "Clear; relevant for urological health.", "8/10"),
    (39, "Do you have a support system in place?", 39, "Who do you rely on for support?", 
 "Good; useful for understanding mental health resources.", "6/10"),
    (40, "Have you traveled recently?", 40, "Where have you traveled to in the last month?", 
     "Direct; important for infectious disease assessment.", "8/10"),
    (41, "Do you have any dietary restrictions?", 41, "Are there any foods you avoid?", 
     "Clear; significant for dietary assessment.", "8/10"),
    (42, "Are you experiencing any changes in your sleep patterns?", 42, "Have you noticed any changes in how you sleep?", 
     "Good; important for overall health.", "8/10"),
    (43, "How often do you consume alcohol?", 43, "How many drinks do you have per week?", 
     "Clear; useful for assessing alcohol use.", "8/10"),
    (44, "Do you have any questions about your treatment plan?", 44, "Are there any aspects of your treatment you are unsure about?", 
     "Direct; encourages patient engagement.", "9/10"),
    (45, "Have you experienced any recent falls?", 45, "Have you had any accidents or falls lately?", 
     "Clear; relevant for assessing mobility risks.", "8/10"),
    (46, "What hobbies or activities do you enjoy?", 46, "What do you like to do in your free time?", 
     "Good; useful for understanding lifestyle.", "7/10"),
    (47, "Do you have any fears or phobias?", 47, "Are there things you are particularly afraid of?", 
     "Clear; relevant for mental health assessment.", "7/10"),
    (48, "Have you had any changes in appetite?", 48, "Are you eating more or less than usual?", 
     "Clear; significant for nutritional assessment.", "8/10"),
    (49, "Do you practice any relaxation techniques?", 49, "What methods do you use to relax?", 
     "Good; useful for understanding coping strategies.", "7/10"),
    (50, "How often do you seek medical advice?", 50, "When was the last time you consulted a healthcare professional?", 
 "Good; useful for understanding health-seeking behavior.", "6/10"),
    (52, "Have you noticed any changes in your skin?", 52, "Are there any changes in your skin texture or color?", 
     "Good; important for dermatological assessment.", "8/10"),
    (53, "Do you feel safe in your home environment?", 53, "Are there any safety concerns at home?", 
     "Clear; relevant for mental well-being.", "8/10"),
    (54, "Are you experiencing any symptoms of depression?", 54, "Have you felt down or hopeless lately?", 
     "Direct; crucial for mental health screening.", "9/10"),
    (55, "How often do you visit your doctor?", 55, "When was your last medical check-up?", 
     "Clear; useful for understanding health maintenance.", "8/10"),
    (56, "Have you had any recent lab tests?", 56, "When was your last blood test?", 
     "Clear; relevant for ongoing health monitoring.", "8/10"),
    (57, "Do you use any alternative therapies?", 57, "Are you seeing any practitioners for non-traditional treatments?", 
     "Good; useful for understanding comprehensive care.", "7/10"),
    (58, "Are you involved in any community activities?", 58, "Do you participate in local events or groups?", 
     "Clear; relevant for social support assessment.", "7/10"),
    (59, "Do you have any history of substance abuse?", 59, "Have you ever had issues with drugs or alcohol?", 
     "Direct; important for health assessment.", "9/10"),
    (60, "Are you experiencing any changes in libido?", 60, "Have you noticed any changes in your sexual desire?", 
     "Clear; relevant for sexual health assessment.", "8/10"),
    (61, "Do you feel comfortable discussing your health?", 61, "Do you find it easy to talk about health issues?", 
     "Good; important for patient-doctor communication.", "8/10"),
    (62, "Have you noticed any changes in your nails?", 62, "Are your nails breaking or changing in appearance?", 
     "Clear; significant for overall health.", "7/10"),
    (63, "How often do you see a dentist?", 63, "When was your last dental appointment?", 
     "Clear; relevant for oral health.", "8/10"),
    (64, "Do you experience any issues with your vision?", 64, "Have you had any changes in your eyesight?", 
     "Direct; crucial for eye health assessment.", "9/10"),
    (65, "Do you have any dietary allergies?", 65, "Are there any foods you are allergic to?", 
     "Clear; important for nutritional safety.", "9/10"),
    (66, "How do you handle conflicts or disagreements?", 66, "What strategies do you use in conflict resolution?", 
     "Good; useful for understanding interpersonal skills.", "7/10"),
    (67, "Do you have any concerns about aging?", 67, "Are there specific aging-related issues you worry about?", 
     "Clear; relevant for geriatric health.", "8/10"),
    (68, "Have you ever experienced abuse or trauma?", 68, "Have you been through any traumatic events?", 
     "Direct; sensitive but important for mental health.", "9/10"),
    (69, "Do you feel that you have a purpose in life?", 69, "What motivates you on a daily basis?", 
     "Good; relevant for mental well-being.", "8/10"),
    (70, "Have you changed your routine recently?", 70, "Have you altered any daily habits?", 
     "Clear; significant for lifestyle assessment.", "7/10"), # New diverse questions
    (71, "What symptoms are you experiencing right now?", 71, "What symptoms are you experiencing right now?", 
     "Clear; prompts for specific symptoms.", "8/10"),
    (72, "How has your appetite changed lately?", 72, "Have you noticed changes in your eating habits?", 
     "Good; relevant for assessing nutritional health.", "8/10"),
    (73, "Do you have any chronic health conditions?", 73, "What chronic conditions do you have?", 
     "Direct; important for medical history.", "9/10"),
    (74, "How often do you engage in physical activity?", 74, "How frequently do you exercise?", 
     "Clear; useful for evaluating lifestyle choices.", "8/10"),
    (75, "Have you noticed any changes in your sleep patterns?", 75, "How has your sleep changed recently?", 
     "Relevant; important for overall health assessment.", "8/10"),
    
    (76, "On a scale from 1 to 10, how stressed do you feel today?", 76, "How would you rate your current stress level?", 
     "Clear; helpful for understanding mental health.", "8/10"),
    (77, "What coping mechanisms do you use when feeling anxious?", 77, "How do you manage anxiety?", 
     "Good; significant for mental health evaluation.", "8/10"),
    (78, "Have you experienced any mood swings recently?", 78, "Have your emotions been fluctuating?", 
     "Relevant; important for mental well-being.", "7/10"),
    (79, "Do you have someone you can talk to about your feelings?", 79, "Who do you confide in for emotional support?", 
     "Good; important for social support assessment.", "8/10"),
    (80, "How do you manage your mental well-being?", 80, "What strategies do you use for your mental health?", 
     "Useful; encourages proactive health management.", "8/10"),
    
    (81, "Can you describe the type of pain you are feeling?", 81, "What does your pain feel like?", 
     "Direct; prompts for important details on pain.", "8/10"),
    (82, "On a scale of 1 to 10, how would you rate your pain?", 82, "How severe is your pain right now?", 
     "Clear; useful for assessing discomfort.", "9/10"),
    (83, "Do you feel pain more in the morning or at night?", 83, "When do you experience the most pain?", 
     "Good; helps to identify patterns.", "8/10"),
    (84, "Have you tried any treatments for your pain?", 84, "What remedies have you used for your pain?", 
     "Relevant; important for treatment history.", "8/10"),
    (85, "Is the pain localized or does it spread to other areas?", 85, "Where do you feel the pain?", 
     "Clear; essential for diagnosis.", "9/10"),
    
    # Additional preventive health questions
    (86, "When was your last health check-up?", 86, "How recently did you visit a doctor?", 
     "Important; useful for monitoring health.", "8/10"),
    (87, "Do you have regular screenings for any specific health conditions?", 87, "What screenings do you participate in?", 
     "Clear; relevant for preventive care.", "8/10"),
    (88, "How do you stay informed about health issues?", 88, "Where do you get your health information?", 
     "Useful; important for understanding health literacy.", "7/10"),
    (89, "Have you ever participated in any health workshops or seminars?", 89, "What health events have you attended?", 
     "Good; relevant for community involvement.", "7/10"),
    (90, "What steps do you take to prevent illness?", 90, "How do you keep yourself healthy?", 
     "Clear; encourages preventive health behaviors.", "8/10"),
    
    # Follow-up questions
    (91, "Have your symptoms improved or worsened since our last discussion?", 91, "What changes have you noticed in your symptoms?", 
     "Important; useful for ongoing assessment.", "8/10"),
    (92, "What changes have you made to your health routine recently?", 92, "Have you adjusted any health habits?", 
     "Clear; relevant for monitoring progress.", "8/10"),
    (93, "Do you feel that your healthcare provider understands your concerns?", 93, "How well do you think your provider listens?", 
     "Direct; significant for patient-provider relationship.", "8/10"),
    (94, "What additional information would help you better manage your health?", 94, "What resources do you need for your health?", 
     "Good; encourages proactive engagement.", "8/10"),
    (95, "How do you prioritize your health amid other responsibilities?", 95, "What strategies do you use to manage health and other duties?", 
     "Clear; relevant for lifestyle balance.", "7/10"),
     #negtive examples
      (96, "What do you think about your health?", 96, "How do you feel about your health?", 
     "Too subjective; lacks specific health context.", "4/10"),
    (97, "Have you thought about your health recently?", 97, "Have you been thinking about your health?", 
     "Vague; doesn’t prompt for specific health details.", "3/10"),
    (98, "Are you doing well?", 98, "How are you doing?", 
     "Non-specific; doesn’t elicit meaningful health information.", "2/10"),
    (99, "Do you feel okay?", 99, "Are you feeling alright?", 
     "Too general; does not address specific health concerns.", "3/10"),
    (100, "Is everything fine with your health?", 100, "Is your health okay?", 
     "Too casual; lacks the depth needed for a health assessment.", "2/10"),
    (101, "Do you have any thoughts about your symptoms?", 101, "What are your thoughts on your symptoms?", 
     "Ambiguous; doesn't clarify the type of symptoms.", "4/10"),
    (102, "Is there anything bothering you?", 102, "Are you bothered by anything?", 
     "Very vague; lacks focus on specific health issues.", "3/10"),
    (103, "Are you experiencing any issues?", 103, "Do you have any problems?", 
     "Non-specific; needs more clarity on health matters.", "3/10"),
    (104, "What are your general thoughts on health?", 104, "How do you view health?", 
     "Too abstract; doesn’t facilitate a focused discussion.", "2/10"),
    (105, "Do you want to talk about your health?", 105, "Would you like to discuss your health?", 
     "Indecisive; may not encourage open communication.", "3/10"),(106, "Have you had any health scares in the past?", 106, "What past health experiences have impacted you?", 
     "Relevant; explores historical health challenges.", "8/10"),
    (107, "What role does nutrition play in your daily routine?", 107, "How do you prioritize your diet?", 
     "Clear; important for understanding dietary habits.", "8/10"),
    (108, "How do you approach goal setting for your health?", 108, "What health goals do you have?", 
     "Useful; encourages proactive health management.", "7/10"),
    (109, "What impact does your social life have on your health?", 109, "How do your friendships affect your well-being?", 
     "Good; explores social connections and health.", "8/10"),
    (110, "Do you feel comfortable asking questions during medical appointments?", 110, "How do you communicate with your healthcare provider?", 
     "Direct; significant for patient engagement.", "8/10"),
    (111, "Have you noticed any changes in your energy levels?", 111, "How has your energy fluctuated recently?", 
     "Clear; relevant for overall health assessment.", "8/10"),
    (112, "What is your preferred method of relaxation?", 112, "How do you unwind after a stressful day?", 
     "Good; important for mental well-being.", "8/10"),
    (113, "How do you balance work and personal life?", 113, "What strategies do you use to maintain work-life balance?", 
     "Clear; relevant for lifestyle assessment.", "7/10"),
    (114, "What are your thoughts on preventive healthcare?", 114, "How important do you think preventive care is?", 
     "Useful; encourages discussion on health practices.", "8/10"),
    (115, "Do you engage in any volunteer work?", 115, "How do you contribute to your community?", 
     "Good; explores social responsibility and mental health.", "7/10"),(116, "What is your favorite color?", 116, "What color do you prefer?", 
 "Irrelevant; does not relate to health assessment.", "0/10"),
(117, "How many stars are in the sky?", 117, "Can you count the stars?", 
 "Nonsensical; not applicable to any medical context.", "0/10"),
(118, "If you could be any animal, which would you choose?", 118, "What animal do you identify with?", 
 "Unrelated; not relevant to health inquiries.", "0/10"),
(119, "What is your opinion on chocolate?", 119, "Do you like chocolate?", 
 "Irrelevant; does not contribute to health evaluation.", "0/10"),
(120, "How many shoes do you own?", 120, "What type of shoes do you prefer?", 
 "Unrelated; no connection to health issues.", "0/10"),(121, "What do you think about the weather?", 121, "Do you prefer sunny or rainy days?", 
 "Irrelevant; does not pertain to health topics.", "0/10"),
(122, "What is the best book you have read?", 122, "Can you recommend a good book?", 
 "Nonsensical; not relevant to health assessments.", "0/10"),
(123, "How many languages can you speak?", 123, "Which language do you like the most?", 
 "Unrelated; does not relate to any medical context.", "0/10"),
(124, "What is your favorite hobby?", 124, "Do you enjoy painting or drawing?", 
 "Irrelevant; does not contribute to health evaluations.", "0/10"),
(125, "What music do you listen to?", 125, "Do you prefer pop or classical music?", 
 "Nonsensical; not applicable to health inquiries.", "0/10"),(126, "What color is your pain?", 126, "Can you describe your pain in terms of color?", 
 "Nonsensical; pain cannot be described in colors.", "0/10"),
(127, "Does your pain have a taste?", 127, "How would you describe the taste of your pain?", 
 "Irrelevant; pain cannot be associated with taste.", "0/10"),
(128, "What shape is your pain?", 128, "Can you describe the shape of your pain?", 
 "Nonsensical; pain cannot have a physical shape.", "0/10"),
(129, "If your pain were a movie, what genre would it be?", 129, "What movie best represents your pain?", 
 "Unrelated; comparing pain to movies is not meaningful.", "0/10"),
(130, "Can your pain dance?", 130, "How would your pain move if it could?", 
 "Irrelevant; pain cannot engage in physical activities.", "0/10"),(131, "How would you rate your pain on a scale from 1 to 10?", 131, "What number would best represent your pain?", 
 "Relevant; assessing pain intensity is important.", "8/10"),
(132, "What is the nature of your pain (sharp, dull, throbbing)?", 132, "Can you describe the quality of your pain?", 
 "Relevant; understanding the type of pain aids in diagnosis.", "9/10"),
(133, "When did your pain start?", 133, "Can you pinpoint the onset of your pain?", 
 "Relevant; timing of pain onset is crucial for assessment.", "10/10"),
(134, "What activities worsen your pain?", 134, "Which movements increase your discomfort?", 
 "Relevant; identifying aggravating factors helps in treatment.", "9/10"),
(135, "Have you tried any treatments for your pain?", 135, "What methods have you used to relieve your pain?", 
 "Relevant; treatment history is vital for management.", "10/10"),
(136, "Does your pain radiate to other areas of your body?", 136, "Where else do you feel your pain?", 
 "Relevant; understanding pain distribution assists in diagnosis.", "9/10"),
(137, "How often do you experience pain?", 137, "Is your pain constant or intermittent?", 
 "Relevant; frequency of pain episodes is important for evaluation.", "10/10"),
(138, "What triggers your pain?", 138, "Are there specific activities or situations that initiate your pain?", 
 "Relevant; identifying triggers can lead to better management.", "9/10"),
(139, "How does your pain affect your daily life?", 139, "In what ways does pain limit your activities?", 
 "Relevant; understanding pain's impact on lifestyle is crucial.", "10/10"),
(140, "Have you experienced any changes in your pain over time?", 140, "How has your pain evolved?", 
 "Relevant; monitoring changes in pain can guide treatment adjustments.", "9/10"),(141, "Can you describe the level of pain you're feeling right now?", 141, "What would you say your current pain level is?", 
 "Relevant; assessing current pain intensity is important.", "8/10"),
(142, "What kind of pain are you experiencing (e.g., sharp, dull)?", 142, "How would you characterize your pain?", 
 "Relevant; understanding the type of pain aids in diagnosis.", "9/10"),
(143, "When did you first notice your pain?", 143, "Can you tell me when your pain began?", 
 "Relevant; timing of pain onset is crucial for assessment.", "10/10"),
(144, "Which movements or activities make your pain worse?", 144, "Are there specific actions that increase your pain?", 
 "Relevant; identifying aggravating factors helps in treatment.", "9/10"),
(145, "Have you done anything to manage your pain?", 145, "What treatments or remedies have you attempted for your pain?", 
 "Relevant; treatment history is vital for management.", "10/10"),
(146, "Does your pain extend to any other areas?", 146, "Do you feel your pain in other parts of your body?", 
 "Relevant; understanding pain distribution assists in diagnosis.", "9/10"),
(147, "How frequently do you feel pain?", 147, "Is your pain present all the time or does it come and go?", 
 "Relevant; frequency of pain episodes is important for evaluation.", "10/10"),
(148, "What seems to set off your pain?", 148, "Are there particular situations that trigger your pain?", 
 "Relevant; identifying triggers can lead to better management.", "9/10"),
(149, "In what ways does your pain interfere with your everyday activities?", 149, "How does pain limit what you can do daily?", 
 "Relevant; understanding pain's impact on lifestyle is crucial.", "10/10"),
(150, "Have you noticed any changes in your pain symptoms recently?", 150, "How has the nature of your pain changed over time?", 
 "Relevant; monitoring changes in pain can guide treatment adjustments.", "9/10"),(151, "What brings you in today?", 151, "Why are you here today?", 
 "Clear and direct; effectively gathers the primary reason for the visit.", 
 "9/10"),
(152, "What symptoms are you currently experiencing?", 152, "Can you describe your symptoms?", 
 "Clear; focuses on current experience.", 
 "8/10"),
(153, "How long have you been dealing with these symptoms?", 153, "When did the symptoms start?", 
 "Clearer timeframe; specifies duration.", 
 "4/10"),
(154, "Do you experience the symptoms all the time, or do they fluctuate?", 154, "Are the symptoms constant or do they come and go?", 
 "Clear and relevant; addresses symptom stability.", 
 "8/10"),
(155, "How would you rate your pain or discomfort from 1 (minimal) to 10 (severe)?", 155, "How severe is your discomfort on a scale of 1-10?", 
 "Well-formulated; accurately measures severity.", 
 "9/10"),
(156, "Have you noticed any factors that relieve or exacerbate your symptoms?", 156, "What makes the symptoms better or worse?", 
 "Good; specifies context for clarity.", 
 "8/10"),
(157, "Are there any health issues you’ve been diagnosed with previously?", 157, "Do you have any ongoing health issues?", 
 "Clear; effectively prompts for pre-existing conditions.", 
 "8/10"),
(158, "What medications or dietary supplements are you currently using?", 158, "What medications or supplements are you currently taking?", 
 "Well-phrased; essential for understanding patient history.", 
 "9/10"),
(159, "When was your last surgery or hospital stay?", 159, "Have you had any recent hospital visits?", 
 "Clear; effectively inquires about relevant medical history.", 
 "8/10"),
(160, "Are there any allergies we should be aware of?", 160, "Do you have any allergies?", 
 "Direct and relevant; critical for safety in treatment.", 
 "9/10"),(161, "What hobbies do you enjoy in your free time?", 161, "What activities do you like to do?", 
 "Good; useful for understanding personal interests.", 
 "0/10"),
(162, "How do you usually spend your weekends?", 162, "What do you like to do on your days off?", 
 "Clear; provides insight into lifestyle.", 
 "0/10"),
(163, "What is your favorite book and why?", 163, "Do you have a book that you really enjoy?", 
 "Engaging; encourages sharing of personal interests.", 
 "0/10"),
(164, "Have you traveled to any interesting places recently?", 164, "Where was the last place you visited?", 
 "very bad ;  Non-related; does not pertain to health or medical history.", 
 "0/10"),
(165, "What is your favorite type of music?", 165, "Do you have a preferred music genre?", 
 "Clear; opens a discussion about personal taste.", 
 "0/10"),
(166, "How do you usually relax after a long day?", 166, "What methods do you use to unwind?", 
 "Useful for understanding coping strategies.", 
 "0/10"),
(167, "Do you have a favorite movie or TV show?", 167, "What do you enjoy watching?", 
 "Engaging; invites conversation about entertainment preferences.", 
 "0/10"),
(168, "What is a skill you'd like to learn?", 168, "Are there any new skills you're interested in acquiring?", 
 "Thought-provoking; encourages self-reflection.", 
 "0/10"),
(169, "How do you stay informed about current events?", 169, "What sources do you use for news?", 
 "Clear; relevant for understanding media consumption.", 
 "0/10"),
(170, "What do you think is the most important quality in a friend?", 170, "What traits do you value in friendships?", 
 "Insightful; prompts discussion about relationships.", 
 "0/10"),(171, "How often do you schedule routine check-ups?", 171, "When was your last visit to a healthcare provider?", 
 "Clear; important for understanding healthcare engagement.", 
 "8/10"),
(172, "Have you ever experienced any allergic reactions?", 172, "Have you had any severe allergies in the past?", 
 "Direct; crucial for medical history.", 
 "9/10"),
(173, "Do you monitor your blood pressure regularly?", 173, "How often do you check your blood pressure?", 
 "Useful for assessing cardiovascular health.", 
 "8/10"),
(174, "What preventive measures do you take for your health?", 174, "Are there any health screenings you participate in?", 
 "Good; relevant for understanding health maintenance.", 
 "7/10"),
(175, "Have you noticed any changes in your mental health recently?", 175, "Are you experiencing any mood swings or changes?", 
 "Clear; important for mental health assessment.", 
 "8/10"),
(176, "Do you have a plan for managing chronic conditions?", 176, "How do you manage any ongoing health issues?", 
 "Useful; prompts discussion about management strategies.", 
 "9/10"),
(177, "How do you track your health goals?", 177, "What methods do you use to monitor your health progress?", 
 "Good; relevant for understanding self-management.", 
 "7/10"),
(178, "Are there specific symptoms you monitor regularly?", 178, "What signs do you keep an eye on regarding your health?", 
 "Clear; important for chronic condition management.", 
 "8/10"),
(179, "Do you feel comfortable discussing your health concerns?", 179, "How open are you about sharing health issues with providers?", 
 "Direct; relevant for patient-provider communication.", 
 "8/10"),
(180, "What factors influence your healthcare decisions?", 180, "How do you decide on treatment options?", 
 "Insightful; encourages discussion on health literacy.", 
 "7/10"),(181, "What specific symptoms are you experiencing today?", 181, "Can you describe your main complaint?", 
 "Direct; clarifies the reason for the visit.", 
 "9/10"),
(182, "Can you identify any triggers for how you feel?", 182, "Are there particular situations that affect your mood?", 
 "Useful; helps identify contributing factors.", 
 "8/10"),
(183, "How long have you been experiencing these symptoms?", 183, "When did you first notice these changes?", 
 "Important for understanding symptom duration.", 
 "9/10"),
(184, "Do you notice any pattern in your symptoms throughout the day?", 184, "Are your symptoms worse at certain times?", 
 "Clarifies symptom variability.", 
 "8/10"),
(185, "How does the pain interfere with your daily activities?", 185, "Does the discomfort limit your ability to function?", 
 "Useful for assessing impact on quality of life.", 
 "9/10"),
(186, "Have you tried any treatments or remedies for your symptoms?", 186, "What have you done to alleviate your discomfort?", 
 "Clarifies prior interventions.", 
 "8/10"),
(187, "What other medical conditions are you being treated for?", 187, "Do you have any other health issues we should consider?", 
 "Important for comprehensive care.", 
 "9/10"),
(188, "Have you discussed your medications with a healthcare provider recently?", 188, "When was your last medication review?", 
 "Useful for ensuring safe medication management.", 
 "8/10"),
(189, "What prompted your recent surgery or hospitalization?", 189, "Can you explain the reason for your recent medical intervention?", 
 "Clarifies medical history.", 
 "9/10"),
(190, "Have you experienced any allergic reactions in the past?", 190, "Can you describe any severe allergies you've had?", 
 "Important for safety during treatment.", 
 "9/10"),
(191, "How does your exercise routine affect your health?", 191, "What benefits do you notice from exercising regularly?", 
 "Useful for assessing lifestyle impact.", 
 "8/10"),
(192, "What changes have you made to your diet recently?", 192, "Have you altered your eating habits in any way?", 
 "Clarifies dietary influences on health.", 
 "8/10"),
(193, "How do your smoking or drinking habits affect your health?", 193, "What effects have you noticed from these habits?", 
 "Important for understanding lifestyle risks.", 
 "8/10"),
(194, "Have you had any sleep disturbances recently?", 194, "Are you experiencing any issues falling or staying asleep?", 
 "Useful for assessing sleep quality.", 
 "8/10"),
(195, "What chronic conditions are present in your family?", 195, "Are there any hereditary health issues in your family?", 
 "Important for risk assessment.", 
 "9/10"),
(196, "What specific genetic conditions have been identified in your family?", 196, "Are there known hereditary diseases in your lineage?", 
 "Clarifies genetic risk factors.", 
 "9/10"),
(197, "How do you manage your emotional well-being?", 197, "What strategies do you use to cope with stress?", 
 "Useful for understanding mental health management.", 
 "8/10"),
(198, "Have you sought help for changes in your mood or behavior?", 198, "Do you discuss mood changes with a provider?", 
 "Important for addressing mental health concerns.", 
 "9/10"),
(199, "What coping mechanisms do you use for stress or anxiety?", 199, "How do you handle stress in your daily life?", 
 "Useful for assessing mental health strategies.", 
 "8/10"),
(200, "What other symptoms accompanied your fever or chills?", 200, "Have you experienced any other signs of illness?", 
 "Important for assessing possible infections.", 
 "9/10"),
(201, "How long have you been noticing changes in your weight?", 201, "What prompted you to track your weight changes?", 
 "Clarifies health tracking importance.", 
 "9/10"),
(202, "What specific mobility issues are you facing?", 202, "Can you describe any recent falls or balance concerns?", 
 "Useful for assessing physical health.", 
 "9/10"),
(203, "What changes have you observed in your senses?", 203, "Have you experienced any recent sensory changes?", 
 "Important for neurological assessment.", 
 "9/10"),
(204, "What symptoms do you associate with your digestive issues?", 204, "Can you describe any specific gastrointestinal concerns?", 
 "Useful for assessing digestive health.", 
 "9/10"),
(205, "What other respiratory symptoms do you have?", 205, "Are there any additional breathing issues you're facing?", 
 "Clarifies respiratory health concerns.", 
 "9/10"),
(206, "What is your current blood pressure reading?", 206, "Have you had your blood pressure checked recently?", 
 "Important for assessing cardiovascular health.", 
 "9/10"),
(207, "Have you been diagnosed with diabetes?", 207, "What type of diabetes do you have, if any?", 
 "Direct; essential for understanding health risks.", 
 "9/10"),
(208, "What is your current weight and height?", 208, "Can you provide your BMI or weight history?", 
 "Useful for evaluating weight-related health issues.", 
 "9/10"),
(209, "How often do you monitor your blood sugar levels?", 209, "When was the last time you checked your blood sugar?", 
 "Important for diabetes management.", 
 "9/10"),
(210, "What medications are you taking to manage diabetes?", 210, "Are you on insulin or other diabetes medications?", 
 "Critical for understanding treatment regimen.", 
 "9/10"),
(211, "Have you experienced any fluctuations in your blood sugar levels?", 211, "What changes have you noticed in your glucose readings?", 
 "Useful for assessing diabetes control.", 
 "9/10"),
(212, "Do you follow a specific diet for managing your diabetes?", 212, "What dietary changes have you made for blood sugar control?", 
 "Important for understanding lifestyle adjustments.", 
 "9/10"),
(213, "Have you experienced any diabetes-related complications?", 213, "What symptoms or issues related to diabetes have you encountered?", 
 "Critical for assessing overall health impact.", 
 "9/10"),
(214, "What is your target blood pressure goal?", 214, "Do you have a specific blood pressure target set by your doctor?", 
 "Useful for managing cardiovascular risk.", 
 "9/10"),
(215, "How often do you exercise to help manage your diabetes?", 215, "What type of physical activity do you engage in regularly?", 
 "Important for assessing lifestyle habits.", 
 "9/10"),
(216, "How do you manage your blood sugar levels daily?", 216, "What steps do you take to maintain stable blood glucose?", 
 "Important for understanding daily diabetes management.", 
 "9/10"),
(217, "What symptoms do you experience when your blood sugar is high or low?", 217, "Can you describe any signs of hyperglycemia or hypoglycemia?", 
 "Useful for assessing awareness of diabetes symptoms.", 
 "9/10"),
(218, "Have you had any recent diabetes education or counseling?", 218, "When did you last attend a diabetes education session?", 
 "Important for evaluating support and knowledge.", 
 "9/10"),
(219, "Do you monitor your cholesterol levels regularly?", 219, "What were your last cholesterol results?", 
 "Critical for assessing cardiovascular health in diabetes.", 
 "9/10"),
(220, "What is your typical daily carbohydrate intake?", 220, "How do you track your carb consumption?", 
 "Useful for managing blood sugar through diet.", 
 "9/10"),
(221, "Have you made any lifestyle changes to control your blood pressure?", 221, "What modifications have you implemented for hypertension management?", 
 "Important for assessing lifestyle interventions.", 
 "9/10"),
(222, "How often do you visit your healthcare provider for diabetes management?", 222, "What is the frequency of your check-ups?", 
 "Useful for evaluating ongoing care.", 
 "9/10"),
(223, "What do you consider to be your biggest challenge in managing diabetes?", 223, "Are there specific areas where you struggle with control?", 
 "Important for understanding patient difficulties.", 
 "9/10"),
(224, "Do you have a plan for what to do in case of a blood sugar emergency?", 224, "What steps do you take if you experience severe hypoglycemia?", 
 "Critical for ensuring safety in diabetes management.", 
 "9/10"),
(225, "How do you feel about your current diabetes management plan?", 225, "What aspects of your treatment are working well for you?", 
 "Useful for assessing patient satisfaction and effectiveness.", 
 "9/10"),
(226, "Have you experienced any episodes of diabetic ketoacidosis?", 226, "When was the last time you had symptoms of ketoacidosis?", 
 "Important for assessing severe diabetes complications.", 
 "9/10"),
(227, "What strategies do you use to prevent diabetes complications?", 227, "How do you manage your risk factors for complications?", 
 "Useful for understanding preventive measures.", 
 "9/10"),
(228, "How do you track your daily physical activity?", 228, "What methods do you use to log your exercise?", 
 "Important for managing diabetes through activity.", 
 "9/10"),
(229, "Do you have regular appointments with a dietitian?", 229, "How often do you consult with a nutritionist for your diabetes?", 
 "Critical for nutritional management.", 
 "9/10"),
(230, "What role does stress play in your diabetes management?", 230, "How do you cope with stress related to your health?", 
 "Useful for assessing emotional health impacts.", 
 "9/10"),
(231, "Have you noticed any changes in your skin health?", 231, "Do you have any skin conditions related to diabetes?", 
 "Important for recognizing diabetes-related skin issues.", 
 "9/10"),
(232, "How often do you check for diabetic neuropathy symptoms?", 232, "What signs of nerve damage do you monitor for?", 
 "Critical for early detection of complications.", 
 "9/10"),
(233, "Have you been educated on foot care for diabetics?", 233, "What steps do you take to care for your feet?", 
 "Important for preventing foot-related complications.", 
 "9/10"),
(234, "What is your current body mass index (BMI)?", 234, "How do you track your weight in relation to diabetes?", 
 "Useful for evaluating weight management efforts.", 
 "9/10"),
(235, "Have you experienced any changes in your kidney function?", 235, "When was your last kidney function test?", 
 "Critical for assessing diabetes-related kidney health.", 
 "9/10"),
(236, "What is your favorite color?", 236, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(237, "Do you like to travel?", 237, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(238, "What is your favorite food?", 238, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(239, "What hobbies do you enjoy?", 239, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(240, "Do you have a favorite movie?", 240, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(241, "What type of music do you prefer?", 241, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(242, "Do you have any pets?", 242, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(243, "What is your dream vacation destination?", 243, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(244, "What is your favorite season?", 244, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(245, "Do you enjoy reading books?", 245, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(246, "Pain", 246, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(247, "Happiness", 247, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(248, "Sunshine", 248, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(249, "Music", 249, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(250, "Travel", 250, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(251, "Food", 251, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(252, "Sleep", 252, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(253, "Exercise", 253, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(254, "Friends", 254, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(255, "Nature", 255, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(256, "Pain", 256, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(257, "Joy", 257, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(258, "Clouds", 258, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(259, "Water", 259, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(260, "Books", 260, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(261, "Art", 261, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(262, "Dance", 262, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(263, "Technology", 263, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(264, "Dreams", 264, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(265, "Health", 265, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(266, "Pain", 266, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(267, "Hope", 267, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(268, "Sky", 268, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(269, "Food", 269, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(270, "Family", 270, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(271, "Adventure", 271, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(272, "Joy", 272, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(273, "Ocean", 273, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(274, "Game", 274, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(275, "Peace", 275, "I don't know", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(276, "I don't know", 276, "Pain", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(277, "I don't know", 277, "Hope", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(278, "I don't know", 278, "Sky", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(279, "I don't know", 279, "Food", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(280, "I don't know", 280, "Family", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(281, "I don't know", 281, "Adventure", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(282, "I don't know", 282, "Joy", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(283, "I don't know", 283, "Ocean", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(284, "I don't know", 284, "Game", 
 "Non-related; not relevant to medical history.", 
 "0/10"),
(285, "I don't know", 285, "Peace", 
 "Non-related; not relevant to medical history.", 
 "0/10"),(286, "How are you feeling today?", 286, "How are you feeling today?", 
"Direct; opens conversation about the patient's general well-being.", 
"8/10"),

(287, "Can you describe your current emotional state?", 287, "Can you describe your current emotional state?", 
"Provides a direct prompt for discussing mental health, asking the patient to describe their feelings.", 
"8/10"),

(288, "Are you feeling any discomfort right now?", 288, "Are you feeling any discomfort right now?", 
"Useful for understanding if the patient is experiencing any physical discomfort at the moment.", 
"8/10"),

(289, "How has your mood been over the past few days?", 289, "How has your mood been over the past few days?", 
"Expands on current feelings by prompting the patient to reflect on recent emotional trends.", 
"7/10"),

(290, "What would you rate your overall well-being today on a scale of 1 to 10?", 290, "What would you rate your overall well-being today on a scale of 1 to 10?", 
"Provides a quantitative measure of how the patient is feeling, useful for tracking changes.", 
"9/10"),

(291, "Have you noticed any changes in your physical or emotional health today compared to yesterday?", 291, "Have you noticed any changes in your physical or emotional health today compared to yesterday?", 
"Encourages the patient to reflect on recent changes, useful for dynamic assessments.", 
"8/10"),

(292, "Are you feeling more tired than usual today?", 292, "Are you feeling more tired than usual today?", 
"Prompts for fatigue levels, relevant for understanding overall well-being.", 
"7/10"),
(293, "Why are you here today?", 293, "Why are you here today?", 
"Clear and direct; effectively gathers the primary reason for the visit.", 
"9/10"),

(294, "What brings you in today?", 294, "What brings you in today?", 
"Direct and open-ended; prompts the patient to explain their main concern.", 
"8/10"),

(295, "Can you tell me the reason for your visit?", 295, "Can you tell me the reason for your visit?", 
"Polite and specific; asks the patient to clarify their purpose for the visit.", 
"8/10"),

(296, "What symptoms or concerns prompted you to seek medical help?", 296, "What symptoms or concerns prompted you to seek medical help?", 
"Good for identifying specific issues or symptoms that led to the visit.", 
"9/10"),

(297, "What health issue are you hoping to address today?", 297, "What health issue are you hoping to address today?", 
"Helps focus on the patient’s specific health concern.", 
"8/10"),

(298, "Are there any particular problems you're dealing with that brought you here?", 298, "Are there any particular problems you're dealing with that brought you here?", 
"Encourages the patient to share specific issues.", 
"8/10"),

(299, "Have you experienced any new symptoms that made you come in?", 299, "Have you experienced any new symptoms that made you come in?", 
"Useful for identifying new or acute symptoms that led to the visit.", 
"9/10"),

(300, "Is there a specific concern you'd like to discuss today?", 300, "Is there a specific concern you'd like to discuss today?", 
"Clear; focuses on the patient's main concern for the visit.", 
"9/10"),
(301, "What are your symptoms?", 301, "What are your symptoms?", 
"Direct and clear; prompts the patient to describe their current symptoms.", 
"8/10"),

(302, "Can you describe the symptoms you're experiencing?", 302, "Can you describe the symptoms you're experiencing?", 
"Polite and open-ended; allows the patient to explain their symptoms in detail.", 
"9/10"),

(303, "What specific symptoms have you noticed?", 303, "What specific symptoms have you noticed?", 
"Encourages the patient to specify particular symptoms.", 
"8/10"),

(304, "Are there any other symptoms accompanying your main complaint?", 304, "Are there any other symptoms accompanying your main complaint?", 
"Useful for uncovering additional symptoms that may be related.", 
"9/10"),

(305, "How long have you been experiencing these symptoms?", 305, "How long have you been experiencing these symptoms?", 
"Clarifies the duration of the symptoms for better understanding.", 
"8/10"),

(306, "Have your symptoms changed over time?", 306, "Have your symptoms changed over time?", 
"Helps track symptom progression or changes.", 
"8/10"),

(307, "Are your symptoms constant or do they come and go?", 307, "Are your symptoms constant or do they come and go?", 
"Good for understanding the pattern and frequency of symptoms.", 
"9/10"),

(308, "What symptoms are most bothersome to you right now?", 308, "What symptoms are most bothersome to you right now?", 
"Focuses on the most troubling aspects of the patient's condition.", 
"9/10"),
(309, "Can you describe your pain?", 309, "Can you describe your pain?", 
"Direct; encourages the patient to provide details about the nature of their pain.", 
"8/10"),

(310, "What type of pain are you feeling (e.g., sharp, dull, throbbing)?", 310, "What type of pain are you feeling (e.g., sharp, dull, throbbing)?", 
"Helps classify the pain type, aiding in diagnosis.", 
"9/10"),

(311, "Where exactly do you feel the pain?", 311, "Where exactly do you feel the pain?", 
"Clarifies the location of the pain for better understanding.", 
"9/10"),

(312, "Does the pain spread to other parts of your body?", 312, "Does the pain spread to other parts of your body?", 
"Useful for identifying radiating pain, important for diagnosis.", 
"8/10"),

(313, "How severe is your pain on a scale of 1 to 10?", 313, "How severe is your pain on a scale of 1 to 10?", 
"Provides a quantifiable measure of pain intensity.", 
"9/10"),

(314, "When did your pain start?", 314, "When did your pain start?", 
"Clarifies the onset of pain, which is critical for diagnosis.", 
"9/10"),

(315, "Is your pain constant, or does it come and go?", 315, "Is your pain constant, or does it come and go?", 
"Helps determine the pattern of the pain for more precise assessment.", 
"9/10"),

(316, "What activities or movements make your pain worse?", 316, "What activities or movements make your pain worse?", 
"Helps identify triggers that aggravate the pain.", 
"9/10"),

(317, "Have you tried any treatments to relieve your pain?", 317, "Have you tried any treatments to relieve your pain?", 
"Good for understanding the effectiveness of previous pain management efforts.", 
"8/10"),
(318, "Are you experiencing any other issues?", 318, "Are you experiencing any other issues?", 
"Direct and open-ended; allows the patient to mention any additional problems.", 
"8/10"),

(319, "Are there any other symptoms or concerns that you haven't mentioned yet?", 319, "Are there any other symptoms or concerns that you haven't mentioned yet?", 
"Encourages the patient to share unreported symptoms or concerns.", 
"9/10"),

(320, "Do you have any other health problems that may be related to your current condition?", 320, "Do you have any other health problems that may be related to your current condition?", 
"Useful for identifying related health issues.", 
"8/10"),

(321, "Are there any ongoing health issues you're dealing with?", 321, "Are there any ongoing health issues you're dealing with?", 
"Helps uncover chronic or ongoing issues.", 
"8/10"),

(322, "Have you noticed any new or unusual symptoms lately?", 322, "Have you noticed any new or unusual symptoms lately?", 
"Encourages the patient to reflect on recent changes in their health.", 
"8/10"),

(323, "Are you having any trouble with your daily activities?", 323, "Are you having any trouble with your daily activities?", 
"Helps assess how other issues might be affecting the patient’s day-to-day life.", 
"9/10"),

(324, "Have you experienced any physical or emotional changes recently?", 324, "Have you experienced any physical or emotional changes recently?", 
"Allows for the assessment of both physical and emotional health changes.", 
"8/10"),

(325, "Is there anything else you'd like to discuss regarding your health?", 325, "Is there anything else you'd like to discuss regarding your health?", 
"Encourages the patient to bring up any other concerns they might have.", 
"9/10"),
(326, "When did your symptoms start?", 326, "When did your symptoms start?", 
"Direct and clear; helps determine the onset of symptoms.", 
"9/10"),

(327, "Can you pinpoint the exact time or day your symptoms began?", 327, "Can you pinpoint the exact time or day your symptoms began?", 
"Encourages the patient to specify the exact onset of their symptoms.", 
"8/10"),

(328, "How long have you been experiencing these symptoms?", 328, "How long have you been experiencing these symptoms?", 
"Clarifies the duration of the symptoms for better understanding.", 
"8/10"),

(329, "Did your symptoms come on suddenly or gradually?", 329, "Did your symptoms come on suddenly or gradually?", 
"Helps to understand whether the symptoms appeared acutely or developed over time.", 
"9/10"),

(330, "Have your symptoms changed since they first appeared?", 330, "Have your symptoms changed since they first appeared?", 
"Useful for tracking progression or worsening of symptoms.", 
"8/10"),

(331, "Were you doing anything specific when the symptoms started?", 331, "Were you doing anything specific when the symptoms started?", 
"Helps to identify any activities or events that might have triggered the symptoms.", 
"9/10"),

(332, "Have your symptoms been consistent since they started, or have they come and gone?", 332, "Have your symptoms been consistent since they started, or have they come and gone?", 
"Clarifies whether the symptoms are persistent or intermittent.", 
"9/10"),

(333, "Can you recall if there were any changes in your health just before the symptoms started?", 333, "Can you recall if there were any changes in your health just before the symptoms started?", 
"Prompts the patient to think about any precursor events or health changes.", 
"8/10"),

(334, "Did you notice any warning signs before your symptoms began?", 334, "Did you notice any warning signs before your symptoms began?", 
"Helps identify early indicators or prodromal symptoms.", 
"8/10"),
(335, "Are you experiencing any other issues?", 335, "Are you experiencing any other issues?", 
"Direct and open-ended; encourages the patient to mention additional concerns.", 
"8/10"),

(336, "Have you noticed any other symptoms that may be related to your current condition?", 336, "Have you noticed any other symptoms that may be related to your current condition?", 
"Helps uncover related symptoms that the patient might not have mentioned.", 
"8/10"),

(337, "Besides your main concern, is there anything else bothering you?", 337, "Besides your main concern, is there anything else bothering you?", 
"Allows the patient to voice additional health concerns.", 
"8/10"),

(338, "Are you dealing with any new or worsening symptoms?", 338, "Are you dealing with any new or worsening symptoms?", 
"Helps determine if there are new developments in the patient's health.", 
"9/10"),

(339, "Have you had any unusual sensations or discomforts that you haven't mentioned?", 339, "Have you had any unusual sensations or discomforts that you haven't mentioned?", 
"Encourages the patient to think about any symptoms they may have overlooked.", 
"8/10"),

(340, "Are there any ongoing issues that you believe may be connected to your current symptoms?", 340, "Are there any ongoing issues that you believe may be connected to your current symptoms?", 
"Prompts the patient to consider how their health problems might be related.", 
"8/10"),

(341, "Is there any other health concern you'd like to discuss today?", 341, "Is there any other health concern you'd like to discuss today?", 
"Allows for further exploration of the patient's health beyond the main complaint.", 
"9/10"),

(342, "Have you noticed any changes in other areas of your health?", 342, "Have you noticed any changes in other areas of your health?", 
"Encourages a broader reflection on the patient's overall health.", 
"8/10"),(343, "When did your symptoms start?", 343, "When did your symptoms start?", 
"Direct and clear; helps determine the onset of symptoms.", 
"9/10"),

(344, "Can you remember what you were doing when the symptoms first appeared?", 344, "Can you remember what you were doing when the symptoms first appeared?", 
"Helps identify possible triggers or activities associated with the onset.", 
"8/10"),

(345, "Have the symptoms been present since a particular event or incident?", 345, "Have the symptoms been present since a particular event or incident?", 
"Helps link the symptoms to a potential cause or event.", 
"8/10"),

(346, "Did the symptoms come on suddenly or gradually develop?", 346, "Did the symptoms come on suddenly or gradually develop?", 
"Useful for distinguishing between acute and chronic conditions.", 
"9/10"),

(347, "Were you feeling fine before the symptoms started?", 347, "Were you feeling fine before the symptoms started?", 
"Clarifies whether the symptoms began abruptly or were preceded by other issues.", 
"7/10"),

(348, "Have you experienced these symptoms before, or is this the first time?", 348, "Have you experienced these symptoms before, or is this the first time?", 
"Good for identifying recurring issues or new conditions.", 
"8/10"),

(349, "Did anything unusual happen before the symptoms began?", 349, "Did anything unusual happen before the symptoms began?", 
"Helps identify any unusual events or factors linked to the onset.", 
"8/10"),

(350, "How long after [a specific event or trigger] did your symptoms appear?", 350, "How long after [a specific event or trigger] did your symptoms appear?", 
"Helps connect the timing of the symptoms to specific events or triggers.", 
"9/10"),

(351, "Have your symptoms stayed the same since they began, or have they changed over time?", 351, "Have your symptoms stayed the same since they began, or have they changed over time?", 
"Useful for assessing progression or worsening of the symptoms.", 
"9/10"),(352, "Can you describe any specific events or activities that preceded the onset of your symptoms?", 352, "Can you describe any specific events or activities that preceded the onset of your symptoms?", 
"Directly links the onset of symptoms to specific triggers or activities.", 
"10/10"),

(353, "When was the last time you felt completely well before your symptoms started?", 353, "When was the last time you felt completely well before your symptoms started?", 
"Vague; doesn't prompt for specific details about the onset of symptoms.", 
"3/10"),(354, "Have you taken any medication?", 354, "Have you taken any medication?", 
"Direct; prompts the patient to disclose any medications they are currently taking.", 
"9/10"),

(355, "What medications are you currently taking?", 355, "What medications are you currently taking?", 
"Encourages the patient to list all medications for comprehensive assessment.", 
"10/10"),

(356, "Have you taken any over-the-counter medications recently?", 356, "Have you taken any over-the-counter medications recently?", 
"Helps identify non-prescription drugs that may affect the patient's condition.", 
"8/10"),

(357, "Have you recently stopped taking any medications?", 357, "Have you recently stopped taking any medications?", 
"Useful for understanding changes in medication that could impact health.", 
"8/10"),

(358, "Do you have any allergies to medications?", 358, "Do you have any allergies to medications?", 
"Critical for ensuring patient safety and avoiding adverse reactions.", 
"9/10"),

(359, "Have you experienced any side effects from the medications you're taking?", 359, "Have you experienced any side effects from the medications you're taking?", 
"Important for assessing the impact of medication on the patient's health.", 
"9/10"),

(360, "Are you taking any supplements or herbal remedies in addition to your medications?", 360, "Are you taking any supplements or herbal remedies in addition to your medications?", 
"Helps to gather a complete picture of the patient's health regimen.", 
"8/10"),

(361, "When did you last take your medication?", 361, "When did you last take your medication?", 
"Clarifies adherence to medication schedules, which is important for effective treatment.", 
"9/10"),

(362, "Have you consulted your doctor about the medications you're taking?", 362, "Have you consulted your doctor about the medications you're taking?", 
"Encourages the patient to consider their healthcare provider's role in their medication management.", 
"8/10"),

(363, "Have you ever had any adverse reactions to medications in the past?", 363, "Have you ever had any adverse reactions to medications in the past?", 
"Critical for understanding the patient's medication history and safety.", 
"9/10"),(364, "Have you taken any medication?", 364, "Have you taken any medication?", 
"Direct; prompts the patient to disclose any medications they are currently taking.", 
"9/10"),

(365, "What medications are you currently taking?", 365, "What medications are you currently taking?", 
"Encourages the patient to list all medications for comprehensive assessment.", 
"10/10"),

(366, "Are you taking any vitamins?", 366, "Are you taking any vitamins?", 
"Vague; does not specify the relevance to the patient's health condition.", 
"4/10"),

(367, "Have you taken anything for your symptoms?", 367, "Have you taken anything for your symptoms?", 
"Could be interpreted broadly; may not specify if referring to medication or other remedies.", 
"5/10"),

(368, "Did you take any pills today?", 368, "Did you take any pills today?", 
"Too general; does not specify what type of medication is being inquired about.", 
"3/10"),

(369, "What color is your medication?", 369, "What color is your medication?", 
"Non-specific; does not contribute to understanding the patient's treatment.", 
"1/10"),

(370, "Are you taking medication for your health?", 370, "Are you taking medication for your health?", 
"Very vague; lacks detail and context, making it less useful.", 
"2/10"),

(371, "Do you like taking medication?", 371, "Do you like taking medication?", 
"Unrelated to medical history; does not provide useful information.", 
"0/10"),

(372, "Have you ever thought about taking medication?", 372, "Have you ever thought about taking medication?", 
"Very vague; does not inquire about current medication use or history.", 
"2/10"),

(373, "What’s your favorite medication?", 373, "What’s your favorite medication?", 
"Non-relevant; does not pertain to the patient's health or treatment.", 
"0/10"),(374, "Did you take your medication as prescribed?", 374, "Did you take your medication as prescribed?", 
"Direct and clear; essential for assessing medication adherence.", 
"10/10"),

(375, "Did you experience any side effects from the medication?", 375, "Did you experience any side effects from the medication?", 
"Important for understanding the impact of treatment on the patient.", 
"9/10"),

(376, "Did you notice any changes in your symptoms after starting the medication?", 376, "Did you notice any changes in your symptoms after starting the medication?", 
"Useful for evaluating the effectiveness of the treatment.", 
"9/10"),

(377, "Did you ever skip a dose of your medication?", 377, "Did you ever skip a dose of your medication?", 
"Important for assessing adherence and potential impact on health.", 
"8/10"),

(378, "Did you inform your doctor about all the medications you're taking?", 378, "Did you inform your doctor about all the medications you're taking?", 
"Critical for ensuring safe and effective treatment.", 
"9/10"),

(379, "Did you feel any improvement in your condition after taking the medication?", 379, "Did you feel any improvement in your condition after taking the medication?", 
"Encourages reflection on treatment outcomes.", 
"8/10"),

(380, "Did you have any allergic reactions to the medication?", 380, "Did you have any allergic reactions to the medication?", 
"Essential for assessing safety and monitoring adverse effects.", 
"10/10"),

(381, "Did you take any other medications at the same time?", 381, "Did you take any other medications at the same time?", 
"Important for understanding potential interactions.", 
"9/10"),

(382, "Did you find it difficult to take your medication as directed?", 382, "Did you find it difficult to take your medication as directed?", 
"Helpful for identifying barriers to adherence.", 
"7/10"),

(383, "Did you ever change your medication without consulting your doctor?", 383, "Did you ever change your medication without consulting your doctor?", 
"Relevant for understanding patient behavior regarding treatment.", 
"6/10"),(384, "Do you currently take any medication?", 384, "Do you currently take any medication?", 
"Direct; prompts the patient to disclose their current medication use.", 
"9/10"),

(385, "Do you have any concerns about your medication?", 385, "Do you have any concerns about your medication?", 
"Encourages discussion about patient worries and medication safety.", 
"9/10"),

(386, "Do you keep track of your medication schedule?", 386, "Do you keep track of your medication schedule?", 
"Helps assess adherence strategies and patient organization.", 
"8/10"),

(387, "Do you experience any symptoms after taking your medication?", 387, "Do you experience any symptoms after taking your medication?", 
"Useful for monitoring side effects or reactions.", 
"9/10"),

(388, "Do you know the purpose of each medication you're taking?", 388, "Do you know the purpose of each medication you're taking?", 
"Important for patient education and understanding of their treatment.", 
"8/10"),

(389, "Do you feel comfortable discussing your medication with your healthcare provider?", 389, "Do you feel comfortable discussing your medication with your healthcare provider?", 
"Encourages open communication about treatment.", 
"9/10"),

(390, "Do you often forget to take your medication?", 390, "Do you often forget to take your medication?", 
"Helpful for assessing adherence issues.", 
"7/10"),

(391, "Do you consult your doctor before taking any over-the-counter medications?", 391, "Do you consult your doctor before taking any over-the-counter medications?", 
"Critical for ensuring safe medication practices.", 
"9/10"),

(392, "Do you feel that your medication is effective?", 392, "Do you feel that your medication is effective?", 
"Encourages feedback on treatment outcomes.", 
"8/10"),

(393, "Do you enjoy taking your medication?", 393, "Do you enjoy taking your medication?", 
"Unrelated; does not provide useful information for health assessment.", 
"2/10"),(394, "Did you remember to take your medication yesterday?", 394, "Did you remember to take your medication yesterday?", 
"Somewhat relevant; may not provide comprehensive insight into adherence.", 
"2/10"),

(395, "Did you feel any different after taking your medication last time?", 395, "Did you feel any different after taking your medication last time?", 
"Vague; does not specify the type of difference or timeframe.", 
"3/10"),

(396, "Did you ever share your medication with someone else?", 396, "Did you ever share your medication with someone else?", 
"Important for understanding medication safety, but may not apply to everyone.", 
"2/10"),

(397, "Did you have a prescription refill recently?", 397, "Did you have a prescription refill recently?", 
"Could be helpful but may not indicate current adherence or issues.", 
"3/10"),

(398, "Did you follow your doctor's instructions about your medication?", 398, "Did you follow your doctor's instructions about your medication?", 
"Important, but vague; doesn't specify what instructions.", 
"2/10"),(399, "Do you take your medication with food?", 399, "Do you take your medication with food?", 
"Helpful for assessing medication compliance, but may not be universally relevant.", 
"3/10"),

(400, "Do you find it easy to remember to take your medication?", 400, "Do you find it easy to remember to take your medication?", 
"Vague; does not provide concrete information about adherence.", 
"2/10"),

(401, "Do you feel that you need to adjust your medication?", 401, "Do you feel that you need to adjust your medication?", 
"Relevant but subjective; may not lead to actionable insights.", 
"3/10"),

(402, "Do you discuss your medications with family members?", 402, "Do you discuss your medications with family members?", 
"Somewhat relevant; not all patients will involve family in health matters.", 
"2/10"),

(403, "Do you read the instructions on your medication labels?", 403, "Do you read the instructions on your medication labels?", 
"Useful for assessing patient awareness, but not everyone may do this.", 
"3/10"),(404, "Did you watch any interesting shows recently?", 404, "Did you watch any interesting shows recently?", 
"Non-related; does not pertain to health or medical history.", 
"0/10"),

(405, "Did you go to any events this past weekend?", 405, "Did you go to any events this past weekend?", 
"Non-related; does not contribute to understanding the patient's health.", 
"0/10"),

(406, "Did you try any new recipes lately?", 406, "Did you try any new recipes lately?", 
"Non-related; does not provide useful information for health assessment.", 
"0/10"),

(407, "Did you read any good books recently?", 407, "Did you read any good books recently?", 
"Non-related; does not pertain to the patient's medical status.", 
"0/10"),

(408, "Did you spend time with friends or family last week?", 408, "Did you spend time with friends or family last week?", 
"Non-related; does not inform about the patient's health or treatment.", 
"0/10"),(409, "Do you like to travel?", 409, "Do you like to travel?", 
"Non-related; does not contribute to the patient's medical evaluation.", 
"0/10"),

(410, "Do you enjoy listening to music?", 410, "Do you enjoy listening to music?", 
"Non-related; irrelevant to health assessment.", 
"0/10"),

(411, "Do you have a favorite hobby?", 411, "Do you have a favorite hobby?", 
"Non-related; does not pertain to medical concerns.", 
"0/10"),

(412, "Do you prefer coffee or tea?", 412, "Do you prefer coffee or tea?", 
"Non-related; lacks relevance to the patient's health information.", 
"0/10"),

(413, "Do you like to go for walks?", 413, "Do you like to go for walks?", 
"Non-related; does not provide useful medical insight.", 
"0/10"),(414, "When did you last go on vacation?", 414, "When did you last go on vacation?", 
"Non-related; does not pertain to health or medical history.", 
"0/10"),

(415, "When did you start your new job?", 415, "When did you start your new job?", 
"Non-related; irrelevant to medical assessments.", 
"0/10"),

(416, "When did you last attend a concert?", 416, "When did you last attend a concert?", 
"Non-related; does not provide useful information for health evaluation.", 
"0/10"),

(417, "When did you begin your favorite hobby?", 417, "When did you begin your favorite hobby?", 
"Non-related; lacks relevance to the patient's medical status.", 
"0/10"),

(418, "When did you last visit a new restaurant?", 418, "When did you last visit a new restaurant?", 
"Non-related; does not contribute to understanding the patient's health.", 
"0/10"),

]
# Create a DataFrame from the new questions data
df = pd.DataFrame(new_questions, columns=[
    'New Question ID', 
    'New Question', 
    'Original Question ID', 
    'Original Question', 
    'Evaluation', 
    'Rating'
])

# Save the DataFrame to a CSV file
df.to_csv('evaluation_data.csv', index=False)

print("CSV file 'evaluation_data.csv' created successfully.")